version: "3"
services:
  graphql:
    container_name: hydra-graphql
    image: shahcompbio/hydra-graphql
    volumes:
      - ./.env:/root/.env
      - ./data.xls:/root/lib/utils/s.xls
  frontend:
    container_name: hydra-frontend
    image: shahcompbio/hydra-react
    ports:
      - "5005:80"
